"""
V3 Native Host installer — Self-Register implementation (Windows only for now).

Writes the Native-Host-Manifest JSON to disk plus a registry entry that
points Chrome at it. Idempotent: re-running on an installed system is a
no-op when the manifest content matches.

Cross-OS (macOS, Linux) lands in Issue #13; this walking-skeleton version
covers Windows because that's the ADR-0001 risk-validation target.

Usage:

    python native_host/install.py

Chrome only accepts Native Messaging from origins listed in the manifest's
``allowed_origins``, so the host must know the extension's ID up front.
``chrome_extension/manifest.json`` pins a ``key``, which makes Chrome derive
the same ID on every machine — so the ID is a constant here rather than
something the user has to read off ``chrome://extensions``. Override it with
``--extension-id`` when loading a build whose ``key`` was stripped (for
instance one installed from the Chrome Web Store, which issues its own).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HOST_NAME = "com.kicad_parts_importer.host"
REGISTRY_KEY_PATH = rf"Software\Google\Chrome\NativeMessagingHosts\{HOST_NAME}"

# Derived from the "key" pinned in chrome_extension/manifest.json:
# sha256(DER public key), first 16 bytes, hex digits 0-f mapped onto a-p.
DEFAULT_EXTENSION_ID = "ajbbipncafmnckigkalhbhpnmjldniao"


def build_manifest(host_path: Path, extension_id: str) -> dict[str, object]:
    """Build the Native-Host-Manifest dict per the Chrome Native Messaging spec."""
    return {
        "name": HOST_NAME,
        "description": "KiCad Parts Importer V3 native host (walking skeleton)",
        "path": str(host_path.resolve()),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{extension_id}/"],
    }


def manifest_target_path(repo_root: Path) -> Path:
    """The on-disk location of the Native-Host-Manifest JSON file."""
    return repo_root / "native_host" / "_generated" / f"{HOST_NAME}.json"


def host_executable_path(repo_root: Path) -> Path:
    """The path Chrome invokes — a runtime .bat that pins the venv-Python.

    Generated rather than checked in because the path to the user's Python
    interpreter is host-specific. The committed ``kicad-host.bat`` is a
    fallback for manual smoke-testing inside an activated venv; Chrome uses
    this generated shim so it gets the venv interpreter (with
    ``easyeda2kicad`` installed) regardless of subprocess PATH.
    """
    return repo_root / "native_host" / "_generated" / "host-launcher.bat"


def write_runtime_bat(bat_path: Path, python_exe: str, host_py: Path) -> bool:
    """Generate the runtime ``.bat`` that pins Chrome's subprocess to a specific Python.

    Returns True if the file content changed (or was newly created), False on
    a no-op idempotent re-run. Path strings are quoted to survive spaces.
    Written via ``write_bytes`` to dodge Windows newline translation, which
    would otherwise turn our CRLF into CRCRLF and break idempotence.
    """
    new_bytes = (
        b"@echo off\r\n"
        b"REM Generated by native_host/install.py. Do not edit by hand.\r\n"
        + f'"{python_exe}" "{host_py}"\r\n'.encode("utf-8")
    )
    bat_path.parent.mkdir(parents=True, exist_ok=True)
    if bat_path.exists() and bat_path.read_bytes() == new_bytes:
        return False
    bat_path.write_bytes(new_bytes)
    return True


def write_manifest(manifest_path: Path, manifest: dict[str, object]) -> bool:
    """Write the manifest JSON. Returns True if changed, False if already up to date."""
    new_content = json.dumps(manifest, indent=2)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    if manifest_path.exists() and manifest_path.read_text(encoding="utf-8") == new_content:
        return False
    manifest_path.write_text(new_content, encoding="utf-8")
    return True


def register_in_windows_registry(manifest_path: Path) -> bool:
    """Write the registry key under HKCU. Returns True if changed, False if already correct."""
    import winreg

    target = str(manifest_path.resolve())
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH, 0, winreg.KEY_READ) as key:
            current, _ = winreg.QueryValueEx(key, "")
            if current == target:
                return False
    except FileNotFoundError:
        pass

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
        winreg.SetValueEx(key, "", 0, winreg.REG_SZ, target)
    return True


def install(extension_id: str, repo_root: Path) -> dict[str, object]:
    """Self-Register entry point. Returns a result dict for callers / tests."""
    manifest_path = manifest_target_path(repo_root)
    host_path = host_executable_path(repo_root)
    host_py = repo_root / "native_host" / "host.py"
    bat_changed = write_runtime_bat(host_path, sys.executable, host_py)
    manifest = build_manifest(host_path, extension_id)
    manifest_changed = write_manifest(manifest_path, manifest)

    registry_changed: bool | None = None
    if sys.platform == "win32":
        registry_changed = register_in_windows_registry(manifest_path)

    return {
        "manifest_path": str(manifest_path),
        "host_path": str(host_path),
        "manifest_changed": manifest_changed,
        "bat_changed": bat_changed,
        "registry_changed": registry_changed,
        "host_name": HOST_NAME,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--extension-id",
        default=DEFAULT_EXTENSION_ID,
        help=(
            "Chrome extension ID. Defaults to the ID pinned by the manifest's "
            f"`key` ({DEFAULT_EXTENSION_ID}); override only for a build whose key was stripped."
        ),
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    result = install(args.extension_id, repo_root)

    print(f"Native Host Manifest: {result['manifest_path']}")
    print(f"Runtime BAT:          {result['host_path']}")
    print(f"Manifest changed:     {result['manifest_changed']}")
    print(f"BAT changed:          {result['bat_changed']}")
    if result["registry_changed"] is not None:
        print(f"Registry changed:     {result['registry_changed']}")
    print(f"Host name:            {result['host_name']}")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
