"""V3 Native Host installer — Self-Register (Windows).

Writes the Native-Host Manifest and the registry entry that points Chrome at
it. Idempotent: re-running on an installed system is a no-op when nothing
changed.

Two shapes, because the host is invoked differently in each:

**Release binary** (PyInstaller, ``sys.frozen``). The executable *is* the
host, so the manifest points straight at ``sys.executable``. The manifest
lives next to Chrome's other per-user data under ``%LOCALAPPDATA%``, because
the binary may sit in Downloads or be moved later.

**From source** (a checkout with a venv). Chrome would otherwise inherit
whatever ``python`` is on the subprocess PATH, which usually lacks the
project's dependencies. So we generate a small ``.bat`` that pins the current
interpreter and point the manifest at that.

Usage:

    python native_host/install.py       # from source
    KiCadPartsImporterHost.exe          # release binary, double-clicked

Chrome only accepts Native Messaging from origins listed in the manifest's
``allowed_origins``, so the host must know the extension's ID up front.
``chrome_extension/manifest.json`` pins a ``key``, which makes Chrome derive
the same ID on every machine — so the ID is a constant here rather than
something the user has to read off ``chrome://extensions``. Override it with
``--extension-id`` when loading a build whose ``key`` was stripped (for
instance one installed from the Chrome Web Store, which issues its own).

macOS and Linux registration is not implemented — see issue #13.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

HOST_NAME = "com.kicad_parts_importer.host"
REGISTRY_KEY_PATH = rf"Software\Google\Chrome\NativeMessagingHosts\{HOST_NAME}"

# Derived from the "key" pinned in chrome_extension/manifest.json:
# sha256(DER public key), first 16 bytes, hex digits 0-f mapped onto a-p.
# tests/test_extension_manifest.py fails if these two ever drift apart.
DEFAULT_EXTENSION_ID = "ajbbipncafmnckigkalhbhpnmjldniao"


def is_frozen() -> bool:
    """True when running from a PyInstaller bundle rather than a checkout."""
    return bool(getattr(sys, "frozen", False))


def default_repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def manifest_dir(repo_root: Path | None = None) -> Path:
    """Directory holding the generated Native-Host Manifest.

    Frozen builds must not write beside the executable — it may live in a
    read-only or transient location (Downloads, a temp extract dir).
    """
    if is_frozen():
        base = os.environ.get("LOCALAPPDATA") or os.environ.get("APPDATA")
        root = Path(base) if base else Path.home()
        return root / "KiCadPartsImporter"
    return (repo_root or default_repo_root()) / "native_host" / "_generated"


def manifest_target_path(repo_root: Path | None = None) -> Path:
    """The on-disk location of the Native-Host Manifest JSON file."""
    return manifest_dir(repo_root) / f"{HOST_NAME}.json"


def host_command_path(repo_root: Path | None = None) -> Path:
    """The path Chrome invokes.

    Frozen: the executable itself. From source: a generated ``.bat`` that pins
    the interpreter (see the module docstring).
    """
    if is_frozen():
        return Path(sys.executable)
    return manifest_dir(repo_root) / "host-launcher.bat"


def build_manifest(host_path: Path, extension_id: str) -> dict[str, object]:
    """Build the Native-Host Manifest dict per the Chrome Native Messaging spec."""
    return {
        "name": HOST_NAME,
        "description": "KiCad Parts Importer native host",
        "path": str(host_path.resolve()),
        "type": "stdio",
        "allowed_origins": [f"chrome-extension://{extension_id}/"],
    }


def write_runtime_bat(bat_path: Path, python_exe: str, host_py: Path) -> bool:
    """Generate the runtime ``.bat`` that pins Chrome's subprocess to a specific Python.

    Returns True if the file content changed (or was newly created), False on
    a no-op idempotent re-run. Path strings are quoted to survive spaces.
    Written via ``write_bytes`` to dodge Windows newline translation, which
    would otherwise turn our CRLF into CRCRLF and break idempotence.
    """
    new_bytes = (
        b"@echo off\r\n"
        b"REM Generated by native_host/install.py. Do not edit by hand.\r\n"
        + f'"{python_exe}" "{host_py}"\r\n'.encode("utf-8")
    )
    bat_path.parent.mkdir(parents=True, exist_ok=True)
    if bat_path.exists() and bat_path.read_bytes() == new_bytes:
        return False
    bat_path.write_bytes(new_bytes)
    return True


def write_manifest(manifest_path: Path, manifest: dict[str, object]) -> bool:
    """Write the manifest JSON. Returns True if changed, False if already up to date."""
    new_content = json.dumps(manifest, indent=2)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    if manifest_path.exists() and manifest_path.read_text(encoding="utf-8") == new_content:
        return False
    manifest_path.write_text(new_content, encoding="utf-8")
    return True


def register_in_windows_registry(manifest_path: Path) -> bool:
    """Write the registry key under HKCU. Returns True if changed, False if already correct."""
    import winreg

    target = str(manifest_path.resolve())
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH, 0, winreg.KEY_READ) as key:
            current, _ = winreg.QueryValueEx(key, "")
            if current == target:
                return False
    except FileNotFoundError:
        pass

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, REGISTRY_KEY_PATH) as key:
        winreg.SetValueEx(key, "", 0, winreg.REG_SZ, target)
    return True


def install(extension_id: str = DEFAULT_EXTENSION_ID, repo_root: Path | None = None) -> dict[str, object]:
    """Self-Register entry point. Returns a result dict for callers / tests."""
    repo_root = repo_root or default_repo_root()
    manifest_path = manifest_target_path(repo_root)
    host_path = host_command_path(repo_root)

    # Only the source install needs a launcher; a frozen binary is its own host.
    bat_changed: bool | None = None
    if not is_frozen():
        bat_changed = write_runtime_bat(host_path, sys.executable, repo_root / "native_host" / "host.py")

    manifest = build_manifest(host_path, extension_id)
    manifest_changed = write_manifest(manifest_path, manifest)

    registry_changed: bool | None = None
    if sys.platform == "win32":
        registry_changed = register_in_windows_registry(manifest_path)

    return {
        "manifest_path": str(manifest_path),
        "host_path": str(host_path),
        "manifest_changed": manifest_changed,
        "bat_changed": bat_changed,
        "registry_changed": registry_changed,
        "host_name": HOST_NAME,
        "extension_id": extension_id,
        "frozen": is_frozen(),
    }


def self_register(extension_id: str = DEFAULT_EXTENSION_ID) -> int:
    """Register this host with Chrome and report what happened.

    Called both by ``main()`` here and by the frozen host when it is launched
    without arguments (i.e. double-clicked rather than started by Chrome).
    """
    if sys.platform != "win32":
        print(
            "Self-Register currently supports Windows only.\n"
            "macOS and Linux registration is tracked in issue #13:\n"
            "  https://github.com/theautomatist/KiCad-Parts-Importer/issues/13",
            file=sys.stderr,
        )
        return 1

    result = install(extension_id)

    print("KiCad Parts Importer — Native Host registered.")
    print()
    print(f"  Manifest:     {result['manifest_path']}")
    print(f"  Host command: {result['host_path']}")
    print(f"  Extension ID: {result['extension_id']}")
    if result["bat_changed"] is not None:
        print(f"  Launcher written: {result['bat_changed']}")
    print(f"  Manifest written: {result['manifest_changed']}")
    print(f"  Registry updated: {result['registry_changed']}")
    print()
    print("Reload the extension in chrome://extensions, then refresh any open LCSC tab.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Register the KiCad Parts Importer Native Host with Chrome.")
    parser.add_argument(
        "--extension-id",
        default=DEFAULT_EXTENSION_ID,
        help=(
            "Chrome extension ID. Defaults to the ID pinned by the manifest's "
            f"`key` ({DEFAULT_EXTENSION_ID}); override only for a build whose key was stripped."
        ),
    )
    args = parser.parse_args()
    return self_register(args.extension_id)


if __name__ == "__main__":
    sys.exit(main())
