"use strict";

/**
 * Classic-script shim for service worker (`importScripts`) and popup
 * (`<script src=...>`). Both load contexts predate ES modules in this
 * extension and cannot `import` an `.mjs` file directly under MV3.
 *
 * **Source of truth:** `chrome_extension/shared/categoryPath.mjs`.
 * **Do not edit this file in isolation.** Keep the function bodies byte-for-byte
 * identical with the canonical ESM; behavioral parity is pinned by
 * `chrome_extension/shared/categoryPath.test.mjs` (the test loads this file as
 * raw text and asserts every exported function produces the same output as
 * the ESM for the shared test corpus).
 *
 * Globals defined: `normalizeCategoryPath`, `canonicalCategoryKey`,
 * `mergeCategoryConfig`, `dedupeCategorySettings`.
 *
 * See CONTEXT.md ("Category Path") and the shared module's header for the
 * normalization rule itself.
 */

function normalizeCategoryPath(raw) {
  if (raw == null || typeof raw !== "string") return "";
  let s = String(raw).replace(/\\/g, "/");
  s = s.replace(/\/+/g, "/").trim();
  if (typeof s.normalize === "function") {
    s = s.normalize("NFC");
  }
  return s
    .split("/")
    .map((seg) => seg.trim())
    .filter(Boolean)
    .join("/");
}

function canonicalCategoryKey(raw) {
  const n = normalizeCategoryPath(raw);
  return n ? n.toLowerCase() : "";
}

function mergeCategoryConfig(a, b) {
  const vp = (x) =>
    x && typeof x.valueParam === "string" && x.valueParam.trim() ? x.valueParam.trim() : "";
  return {
    hidePinNumbers: Boolean(a && a.hidePinNumbers) || Boolean(b && b.hidePinNumbers),
    hidePinNames: Boolean(a && a.hidePinNames) || Boolean(b && b.hidePinNames),
    valueParam: vp(a) || vp(b) || null,
  };
}

function dedupeCategorySettings(raw) {
  if (!raw || typeof raw !== "object") return {};
  /** @type {Map<string, { displayKey: string, cfg: object }>} */
  const map = new Map();
  for (const [k, v] of Object.entries(raw)) {
    if (!v || typeof v !== "object") continue;
    const displayKey = normalizeCategoryPath(k);
    const canon = canonicalCategoryKey(k);
    if (!canon) continue;
    const cfg = {
      hidePinNumbers: Boolean(v.hidePinNumbers),
      hidePinNames: Boolean(v.hidePinNames),
      valueParam:
        typeof v.valueParam === "string" && v.valueParam.trim() ? v.valueParam.trim() : null,
    };
    const prev = map.get(canon);
    if (!prev) {
      map.set(canon, { displayKey, cfg });
    } else {
      prev.cfg = mergeCategoryConfig(prev.cfg, cfg);
      if (displayKey.length > prev.displayKey.length) {
        prev.displayKey = displayKey;
      }
    }
  }
  const out = {};
  for (const { displayKey, cfg } of map.values()) {
    out[displayKey] = cfg;
  }
  return out;
}
