"use strict";

/**
 * Classic-script shim for service worker (``importScripts``). MV3
 * service workers cannot ``import`` an ``.mjs`` file, so this file mirrors
 * ``chrome_extension/shared/confidenceState.mjs`` byte-for-byte at the
 * function-body level and defines its exports as globals on ``globalThis``.
 *
 * **Source of truth:** ``chrome_extension/shared/confidenceState.mjs``.
 * **Do not edit this file in isolation.** Behavioral parity with the ESM
 * is pinned by ``chrome_extension/shared/confidenceState.test.mjs`` (the
 * SW shim's exports are loaded via ``importScripts`` in production; the
 * ``.mjs`` tests cover the canonical implementation).
 *
 * Globals defined: ``matchComponentRule``, ``computeConfidenceState``,
 * ``EASYEDA_FALLBACK_CONFIDENCE``, ``GREEN_CONFIDENCE_THRESHOLD``.
 *
 * Depends on the ``normalizeCategoryPath`` global already loaded by
 * ``categoryPath.js`` (background.js orders ``importScripts`` accordingly).
 */

/** Confidence assigned to an EasyEDA fallback when no Rule / no heuristic match exists. */
const EASYEDA_FALLBACK_CONFIDENCE = 0.5;

/** 🟢 threshold from KONZEPT.md §3.6 — high ≥ 0.85. */
const GREEN_CONFIDENCE_THRESHOLD = 0.85;

/** Confidence assigned when a Rule's Symbol-Template is resolvable in the registered libs. */
const _RULE_TEMPLATE_CONFIDENCE = 0.95;

function _easyedaFallback(layer, reason) {
  return {
    layer,
    choice: { source: "easyeda" },
    confidence: EASYEDA_FALLBACK_CONFIDENCE,
    reasons: reason ? [reason] : [],
    source: "easyeda-fallback",
  };
}

function _isSymbolTemplateResolvable(symbolSource, templateSymbolsByLib) {
  if (!symbolSource || symbolSource.source !== "template") return false;
  const libPath = symbolSource.libPath;
  const name = symbolSource.name;
  if (!libPath || !name) return false;
  if (!templateSymbolsByLib || typeof templateSymbolsByLib !== "object") {
    return false;
  }
  const names = templateSymbolsByLib[libPath];
  return Array.isArray(names) && names.includes(name);
}

function _hasLabelMappingEntries(labelMapping) {
  if (!labelMapping || typeof labelMapping !== "object") return false;
  return Object.keys(labelMapping).length > 0;
}

function _resolveDeepestPrefixRule(categoryPath, categorySettings) {
  if (!categoryPath || !categorySettings || typeof categorySettings !== "object") {
    return null;
  }
  let bestKey = null;
  let bestLen = -1;
  for (const [keyRaw, value] of Object.entries(categorySettings)) {
    if (!keyRaw || !value || typeof value !== "object") continue;
    const K = normalizeCategoryPath(keyRaw);
    if (!K) continue;
    if (categoryPath === K || categoryPath.startsWith(`${K}/`)) {
      if (K.length > bestLen) {
        bestLen = K.length;
        bestKey = keyRaw;
      }
    }
  }
  if (bestKey == null) return null;
  return { key: bestKey, rule: categorySettings[bestKey] };
}

function matchComponentRule(phase1, state) {
  const categoryPath = normalizeCategoryPath(phase1?.categoryPath);
  const categorySettings = state?.categorySettings || null;
  const templateSymbolsByLib = state?.templateSymbolsByLib || null;

  const resolved = _resolveDeepestPrefixRule(categoryPath, categorySettings);
  const rule = resolved?.rule || null;

  const symbolTemplateResolvable = _isSymbolTemplateResolvable(
    rule?.symbolSource,
    templateSymbolsByLib,
  );
  const labelsMapped = _hasLabelMappingEntries(rule?.labelMapping);

  const guards = {
    pinCountOk: true,
    packageFormOk: true,
    templatesResolvable: symbolTemplateResolvable,
    pinPadResolvable: true,
    overwriteClear: true,
  };

  let symbol;
  let footprint;
  if (symbolTemplateResolvable) {
    symbol = {
      layer: "symbol",
      choice: { ...rule.symbolSource },
      confidence: _RULE_TEMPLATE_CONFIDENCE,
      reasons: [`Category Rule "${resolved.key}" symbol template`],
      source: "rule",
    };
    footprint = _easyedaFallback(
      "footprint",
      "footprint follow-up slice — EasyEDA default",
    );
  } else {
    const fallbackReason = resolved ? null : "no Category Rule registered";
    symbol = _easyedaFallback("symbol", fallbackReason);
    footprint = _easyedaFallback("footprint", fallbackReason);
  }

  const aggregateConfidence = symbol.confidence;

  const factors = {
    ruleResolved: Boolean(resolved),
    categoryResolved: Boolean(resolved),
    symbolResolved: symbol.source !== "easyeda-fallback",
    symbolTemplateResolvable,
    labelsMapped,
    footprintResolved: footprint.source !== "easyeda-fallback",
    confidence: aggregateConfidence,
  };

  const stateName = computeConfidenceState(rule, symbol, footprint, factors);

  return {
    ruleKey: resolved?.key ?? null,
    rule,
    symbol,
    footprint,
    state: stateName,
    confidence: aggregateConfidence,
    guards,
  };
}

function computeConfidenceState(rule, _symbol, _footprint, factors) {
  if (!rule) return "white";
  const f = factors || {};
  const greenReady =
    f.ruleResolved === true
    && f.categoryResolved === true
    && f.symbolTemplateResolvable === true
    && f.labelsMapped === true
    && typeof f.confidence === "number"
    && f.confidence >= GREEN_CONFIDENCE_THRESHOLD;
  if (greenReady) return "green";
  return "yellow";
}
