"use strict";

/**
 * Classic-script shim for service worker (``importScripts``). MV3
 * service workers cannot ``import`` an ``.mjs`` file, so this file mirrors
 * ``chrome_extension/shared/confidenceState.mjs`` byte-for-byte at the
 * function-body level and defines its exports as globals on ``globalThis``.
 *
 * **Source of truth:** ``chrome_extension/shared/confidenceState.mjs``.
 * **Do not edit this file in isolation.** Behavioral parity with the ESM
 * is pinned by ``chrome_extension/shared/confidenceState.test.mjs`` (the
 * SW shim's exports are loaded via ``importScripts`` in production; the
 * ``.mjs`` tests cover the canonical implementation).
 *
 * Globals defined: ``matchComponentRule``, ``computeConfidenceState``,
 * ``EASYEDA_FALLBACK_CONFIDENCE``.
 *
 * Depends on the ``normalizeCategoryPath`` global already loaded by
 * ``categoryPath.js`` (background.js orders ``importScripts`` accordingly).
 */

/** Confidence assigned to an EasyEDA fallback when no Rule / no heuristic match exists. */
const EASYEDA_FALLBACK_CONFIDENCE = 0.5;

function _easyedaFallback(layer, reason) {
  return {
    layer,
    choice: { source: "easyeda" },
    confidence: EASYEDA_FALLBACK_CONFIDENCE,
    reasons: reason ? [reason] : [],
    source: "easyeda-fallback",
  };
}

function _resolveDeepestPrefixRule(categoryPath, categorySettings) {
  if (!categoryPath || !categorySettings || typeof categorySettings !== "object") {
    return null;
  }
  let bestKey = null;
  let bestLen = -1;
  for (const [keyRaw, value] of Object.entries(categorySettings)) {
    if (!keyRaw || !value || typeof value !== "object") continue;
    const K = normalizeCategoryPath(keyRaw);
    if (!K) continue;
    if (categoryPath === K || categoryPath.startsWith(`${K}/`)) {
      if (K.length > bestLen) {
        bestLen = K.length;
        bestKey = keyRaw;
      }
    }
  }
  if (bestKey == null) return null;
  return { key: bestKey, rule: categorySettings[bestKey] };
}

function matchComponentRule(phase1, state) {
  const categoryPath = normalizeCategoryPath(phase1?.categoryPath);
  const categorySettings = state?.categorySettings || null;

  const resolved = _resolveDeepestPrefixRule(categoryPath, categorySettings);

  const guards = {
    pinCountOk: true,
    packageFormOk: true,
    templatesResolvable: true,
    pinPadResolvable: true,
    overwriteClear: true,
  };

  const fallbackReason = resolved ? null : "no Category Rule registered";
  const symbol = _easyedaFallback("symbol", fallbackReason);
  const footprint = _easyedaFallback("footprint", fallbackReason);

  const aggregateConfidence = Math.min(symbol.confidence, footprint.confidence);

  const factors = {
    ruleResolved: Boolean(resolved),
    symbolResolved: symbol.source !== "easyeda-fallback",
    footprintResolved: footprint.source !== "easyeda-fallback",
    confidence: aggregateConfidence,
  };

  const stateName = computeConfidenceState(
    resolved?.rule || null,
    symbol,
    footprint,
    factors,
  );

  return {
    ruleKey: resolved?.key ?? null,
    rule: resolved?.rule ?? null,
    symbol,
    footprint,
    state: stateName,
    confidence: aggregateConfidence,
    guards,
  };
}

function computeConfidenceState(rule, _symbol, _footprint, _factors) {
  if (!rule) return "white";
  return "yellow";
}
