name: check-code-style

on:
    pull_request:
        branches: [master, dev]
    push:
        branches: [dev]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
      - uses: pre-commit/action@v3.0.0
